server:
  port: 8888
  
spring:
  # 数据库连接池配置
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/ai_app_dev?autoReconnect=true&useSSL=false&allowMultiQueries=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      initial-size: 5
      min-idle: 5
      max-active: 10
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      connection-properties: {characterEncoding: 'UTF-8'}
      # 数据库连接池控制台相关
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        url-pattern: /druid/*
  
  # redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: root
    timeout: 3000ms
    # 2.2.2redis客户端实现为lettuce
    lettuce:
      pool:
        min-idle: 5       #最小空闲连接数
        max-idle: 10      #最大空闲连接数
        max-active: 20    #最大连接数
        max-wait: 10000ms    #获取连接的最大等待时间（使用负值没有限制）
  
  #aop相关配置（见AopAutoConfiguration）
  aop:
    proxy-target-class: true #为true时用cglib代理，为false时用jdk代理
    
  task:
    # @Async异步任务线程池配置
    execution:
      pool:
        core-size: 5
        max-size: 10
    # @Scheduled定时任务线程池配置
    scheduling:
      pool:
        size: 5

  #springMVC相关配置  mvc:    date-format: yyyy-MM-dd HH:mm:ss
        
     
#mybatis配置
mybatis:
  type-aliases-package: com.hp.base.model
  mapper-locations:
    - classpath*:mybatis/**/*Mapper.xml




# @configurationProperties配置
author:
  name: hupeng
  age: 29
  
